# Generated by Django 6.0.4 on 2026-05-05 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resale_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_physical_intact', models.BooleanField(default=False, verbose_name='Packaging Intact?')),
                ('is_authentic', models.BooleanField(default=False, verbose_name='Authenticity Verified?')),
                ('is_expiry_valid', models.BooleanField(default=False, verbose_name='Expiry Date Clear?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified & Available'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
